# Generated by Django 3.2.25 on 2024-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compares',
            name='co_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
